### PR TITLE
upgraded zkclient dependency to com.101tec:zkclient:0.4

### PR DESCRIPTION
**Pull request by atdixon**
Assuming these zkclient-bridge sources aren't hosted and release elsewhere, I'd love to see a new release w/ this upgraded zclient dependency.

### CODE REVIEW

**Comment by atdixon** [comment]
Thank you for merging my PR.

What is the release process for this project?

If there's anything I can do to help release this to Maven Central, let me know. I have gone through the release process before w/ Maven projects. On sonatype.org, I am user "atdixon".

Thx.

**Comment by Randgalt** [comment]
I’ll try to get it released soon.



On March 10, 2015 at 9:33:50 AM, Aaron Dixon (notifications@github.com) wrote:

Thank you for merging my PR.

What is the release process for this project?

If there's anything I can do to help release this to Maven Central, let me know. I have gone through the release process before w/ Maven projects. On sonatype.org, I am user "atdixon".

Thx.

**Comment by atdixon** [comment]
Much appreciated, thanks.

**Comment by atdixon** [comment]
Any eta on a release? Thx!

**Comment by Randgalt** [comment]
Hey Guys,

Any Eta on this?

====================
Jordan Zimmerman

**Comment by qiangdavidliu** [comment]
I'll take a look and try to release this this week.

**Comment by Randgalt** [comment]
The ZKClient Bridge 3.0.0 has been released. Note: it now references Apache Curator, not Netflix Curator which is years old by now.

**Comment by atdixon** [comment]
Thanks for this release, btw!

**Comment by Randgalt** [comment]
np

**Pull request merged**
